# Multidimensional arrays

Generally in the sciences, you'll need to store multiple points of data. These can be stored within matrices, also known as **_multidimensional arrays_**.

<img src="https://media.licdn.com/dms/image/D4D12AQHrFFdFMJEm7w/article-cover_image-shrink_720_1280/0/1680164729380?e=2147483647&v=beta&t=3gw6Ky5Yohq7J3MfJZFiykja62Txm6lN3GngS8alwF4" >

By the end of this section, you will know:
* [what multidimensional arrays are](#Multidimensional-Arrays)
* [how to index multidimensional array](#Indexing-multidimensional-arrays)

## Multidimensional Arrays

An array with multiple dimensions (i.e., many one dimesional arrays) are defined as **multidimensional arrays**. We create arrays by using the ```array()``` function from [NumPy](Introduction2Functions.ipynb). Multidimensional arrays follow this basic format:

```python
import numpy as np
somearray = np.array([[1st array], [2nd array]...])
```



So far, we have learned about one dimensional (1D) arrays. Now, we will practice creating two dimensional (2D) and three dimensional (3D) arrays. To help you, here is a visualization:

<img src ="https://miro.medium.com/v2/resize:fit:1400/1*X0Dg7QfSYtWhSAu-afi8-g.png" >

In a 1D array, we have only *one row*. This will differ for 2D and 3D arrays.

### 2D arrays

2D arrays are considered as an array of arrays. You can visualize it as a table of rows and columns:
<img src="https://iq.opengenus.org/content/images/2020/12/Array1.png" >

Here is a demo of creating a 2D array:

In [4]:
# import numpy
import numpy as np

# create 2D array
twoD = np.array([[1, 2, 3], [4, 5, 6]])
print(twoD)

[[1 2 3]
 [4 5 6]]


### 3D arrays

3D arrays are considered an array composed of 2D arrays. Its components include rows, columns, and *arrays*. You can visualize it as a cube, or more broken down as "array pages":

<img src ="https://media.geeksforgeeks.org/wp-content/uploads/3D-array.jpg" >

Here is a demo of creating a 3D array:

In [12]:
# import numpy
import numpy as np

# create two 2D arrays
twoD0 = np.array([[1, 2, 3], [4, 5, 6]])
twoD1 = np.array([[7, 8, 9], [10, 11, 12]])

# put both arrays together
threeD = np.array([twoD0, twoD1])
print(threeD)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


## Indexing multidimensional arrays

### Indexing 2D arrays

We can index a row by following this format:

```
array[row #] = [row]
```

In [6]:
# import numpy
import numpy as np

# create 2D array
twoD = np.array([[1, 2, 3], [4, 5, 6]])

# print first row in our 2D array
print(twoD[0])

[1 2 3]


We can index a column by using the ```:```:

```
array[:, column #] = [column]
```

In [9]:
# import numpy
import numpy as np

# create 2D array
twoD = np.array([[1, 2, 3], [4, 5, 6]])

# print second column in our 2D array
print(twoD[:,1])

[2 5]


We can also index one specific value from a desired row and column:

```
array[row #][column #] = value
```

In [8]:
# import numpy
import numpy as np

# create 2D array
twoD = np.array([[1, 2, 3], [4, 5, 6]])

# print the value in the first row, third column of our 2D array
print(twoD[0][2])

3


### Indexing 3D arrays

We can index 3D arrays by following this format:

```
array[array #, row #, column] = desired output
```

We can index a specific array within the 3D array:

```
array[array #, :, :] = array
```

In [13]:
# import numpy
import numpy as np

# create two 2D arrays
twoD0 = np.array([[1, 2, 3], [4, 5, 6]])
twoD1 = np.array([[7, 8, 9], [10, 11, 12]])

# put both arrays together
threeD = np.array([twoD0, twoD1])

# print second array within our 3D array
print(threeD[1, :, :])

[[ 7  8  9]
 [10 11 12]]


We can also index a specific row of an array within the 3D array:

```
array[array #, row #, :] = row of array
```

In [16]:
# import numpy
import numpy as np

# create two 2D arrays
twoD0 = np.array([[1, 2, 3], [4, 5, 6]])
twoD1 = np.array([[7, 8, 9], [10, 11, 12]])

# put both arrays together
threeD = np.array([twoD0, twoD1])

# print first row of the first array within our 3D array
print(threeD[0, 0, :])

[1 2 3]


We can also index a specific column of an array within the 3D array:

```
array[array #, :, column #] = column of array
```

In [2]:
# import numpy
import numpy as np

# create two 2D arrays
twoD0 = np.array([[1, 2, 3], [4, 5, 6]])
twoD1 = np.array([[7, 8, 9], [10, 11, 12]])

# put both arrays together
threeD = np.array([twoD0, twoD1])

# print first column of the second array within our 3D array
print(threeD[1, :, 0])

[ 7 10]


## Exercises

1. Try to index the 3D array defined below to find the 7 and 8.

In [ ]:
# import numpy
import numpy as np

# create two 2D arrays
twoD0 = np.array([[1, 2, 1], [8, 6, 6]])
twoD1 = np.array([[1, 1, 7], [1, 0, 0]])

# insert index code below

2. Use the NumPy function ```shape()``` on the previous 3D array from the first exercise. What does the output represent? Use this function on the 2D array twoD0 from the first exercise. What does this output represent?

In [ ]:
# insert code here

3. Think about how one may create a 4D array. How many arrays do you believe you would need to create this? Try creating one below.

In [ ]:
# insert code here