# Multidimensional Arrays

Generally, you'll need to store *multiple points of data*. These can be stored within matrices, also known as <ins>**multidimensional arrays**</ins>. These can be created using [**NumPy**](Introduction2Functions.ipynb)

<img src="https://media.licdn.com/dms/image/D4D12AQHrFFdFMJEm7w/article-cover_image-shrink_720_1280/0/1680164729380?e=2147483647&v=beta&t=3gw6Ky5Yohq7J3MfJZFiykja62Txm6lN3GngS8alwF4" width = '400'>

By the end of this section, you will learn:
* [**the different types of multidimensional arrays**](#Multidimensional-arrays)
* [**to index multidimensional arrays**](#Indexing-multidimensional-arrays)

## Multidimensional arrays

An array with <ins>**_multiple dimensions_**</ins> (i.e., many one dimensional arrays) are defined as **multidimensional arrays**. We create arrays by using the **```array()```** function from [NumPy](Introduction2Functions.ipynb). **Multidimensional arrays** follow this basic format:

```python
import numpy as np
somearray = np.array([[1st array], [2nd array]...])
```



So far, we have learned about **_one dimensional (1D)_** arrays. Now, we will practice creating [**two dimensional (2D)**](#2D-arrays) and [**three dimensional (3D)**](#3D-arrays) arrays. To help you, here is a visualization:

<img src ="https://miro.medium.com/v2/resize:fit:1400/1*X0Dg7QfSYtWhSAu-afi8-g.png" >

In a **1D array**, we have only **_one row_**. This will differ for **2D and 3D arrays**.

### 2D arrays

**2D arrays** are considered as <ins>**an array of arrays**</ins>. You can visualize it as a table of rows and columns:
<img src="https://iq.opengenus.org/content/images/2020/12/Array1.png" >

Here is a demo of creating a **2D array**:.

In [ ]:
# import numpy
import numpy as np

# create 2D array
twoD = np.array([[1, 2, 3], [4, 5, 6]])
print(twoD)

[[1 2 3]
 [4 5 6]]


### 3D arrays

**3D arrays** are considered <ins>**an array composed of 2D arrays**</ins>. Its components include **rows, columns, and *arrays***. You can visualize it as a cube:

<img src ="https://media.geeksforgeeks.org/wp-content/uploads/3D-array.jpg" >

Here is a demo of creating a **3D array**:

In [ ]:
# import numpy
import numpy as np

# create two 2D arrays
twoD0 = np.array([[1, 2, 3], [4, 5, 6]])
twoD1 = np.array([[7, 8, 9], [10, 11, 12]])

# put both arrays together
threeD = np.array([twoD0, twoD1])
print(threeD)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


## Indexing multidimensional arrays

### Indexing 2D arrays

We can index a row by following this format:

```
array[row #] = [row]
```

In [ ]:
# import numpy
import numpy as np

# create 2D array
twoD = np.array([[1, 2, 3], [4, 5, 6]])

# print first row in our 2D array
print(twoD[0])

[1 2 3]


We can index a column by using **```:```**:

```
array[:, column #] = [column]
```

In [ ]:
# import numpy
import numpy as np

# create 2D array
twoD = np.array([[1, 2, 3], [4, 5, 6]])

# print second column in our 2D array
print(twoD[:,1])

[2 5]


We can also index **_one specific value_** from a desired row and column:

```
array[row #][column #] = value
```

In [ ]:
# import numpy
import numpy as np

# create 2D array
twoD = np.array([[1, 2, 3], [4, 5, 6]])

# print the value in the first row, third column of our 2D array
print(twoD[0][2])

3


### Indexing 3D arrays

We can index 3D arrays by following this format:

```
array[array #, row #, column] = desired output
```

We can index a **specific array** within the 3D array:

```
array[array #, :, :] = array
```

In [ ]:
# import numpy
import numpy as np

# create two 2D arrays
twoD0 = np.array([[1, 2, 3], [4, 5, 6]])
twoD1 = np.array([[7, 8, 9], [10, 11, 12]])

# put both arrays together
threeD = np.array([twoD0, twoD1])

# print second array within our 3D array
print(threeD[1, :, :])

[[ 7  8  9]
 [10 11 12]]


We can also index a **specific row of an array** within the 3D array:

```
array[array #, row #, :] = row of array
```

In [ ]:
# import numpy
import numpy as np

# create two 2D arrays
twoD0 = np.array([[1, 2, 3], [4, 5, 6]])
twoD1 = np.array([[7, 8, 9], [10, 11, 12]])

# put both arrays together
threeD = np.array([twoD0, twoD1])

# print first row of the first array within our 3D array
print(threeD[0, 0, :])

[1 2 3]


We can also index a **specific column of an array** within the 3D array:

```
array[array #, :, column #] = column of array
```

In [ ]:
# import numpy
import numpy as np

# create two 2D arrays
twoD0 = np.array([[1, 2, 3], [4, 5, 6]])
twoD1 = np.array([[7, 8, 9], [10, 11, 12]])

# put both arrays together
threeD = np.array([twoD0, twoD1])

# print first column of the second array within our 3D array
print(threeD[1, :, 0])

[ 7 10]


## Summary

* **[Multidimensional arrays](#Multidimensional-arrays)** are arrays with **_multiple dimensions_**.


* **[Two dimensional arrays](#2D-arrays)** have <ins>**rows** and **columns**</ins>.


* **[Three dimensional arrays](#3D-arrays)** have <ins>**rows**</ins>, <ins>**columns**</ins>, *and* <ins>**_arrays_**</ins>.


* To **[index 2D arrays](#Indexing-2D-arrays)**:
    * For a **specific row**, ```array[row #] = [row]```
    * For a **specific column**, ```array[:, column #] = [column]```
    * For a **specific value**, ```array[row #][column #] = value```


* To **[index 3D arrays](#Indexing-3D-arrays)**:
    * For a **specific array**,  ```array[array #, :, :] = array```
    * For a **specific row of an array**, ```array[array #, row #, :] = row```
    * For a **specific column of an array**, ```array[array #, :, column #] = column```

## Exercises

1. Try to **index the 3D array** defined below to find the 7 and 8.

2. **Use the NumPy function ```shape()```** on the previous 3D array from the first exercise. What does the output represent? Use this function on the 2D array **```twoD0```** from the first exercise. What does this output represent?

3. Think about how one may create a 4D array. How many arrays do you believe you would need to create this? Try creating one below.

### Answers

1. Try to **index the 3D array** defined below to find the 7 and 8.

In [2]:
#answer

# import numpy
import numpy as np

# create two 2D arrays
twoD0 = np.array([[1, 2, 1], [8, 6, 6]])
twoD1 = np.array([[1, 1, 7], [1, 0, 0]])

# insert index code below

2. **Use the NumPy function ```shape()```** on the previous 3D array from the first exercise. What does the output represent? Use this function on the 2D array **```twoD0```** from the first exercise. What does this output represent?

In [3]:
# answer

import numpy as np

# Placeholder arrays (Replace these with your actual arrays)
threeD_array = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]], [[9, 10], [11, 12]]])
twoD_array = np.array([[1, 2, 3], [4, 5, 6]])

# Getting the shape of the 3D array
shape_3D = threeD_array.shape
print("Shape of the 3D array:", shape_3D)

Shape of the 3D array: (3, 2, 2)


3. Think about how one may create a 4D array. How many arrays do you believe you would need to create this? Try creating one below.

In [ ]:
# answer

import numpy as np

# Create a 4D array using nested lists
# This example creates a 2x3x4x5 array filled with zeros
fourD_array = np.zeros((2, 3, 4, 5))

# Print the shape of the 4D array
print("Shape of the 4D array:", fourD_array.shape)

